version: '3.5'

services:
  mongodb:
    container_name: scrapper-mongo
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - scrapper-network
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    restart: unless-stopped

  mongo-express:
    container_name: mongo-express
    image: mongo-express:0.54
    depends_on:
      - mongodb
    networks:
      - scrapper-network
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - '8081:8081'
    restart: unless-stopped

networks:
  scrapper-network:
    driver: bridge

volumes:
  mongodb: